language: node_js
node_js:
  - 6
after_success: npm run coverage
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE docmanagementtest;" -U postgres
  - psql -c "CREATE USER johnboscoohia;" -U postgres
  - npm install -g mocha
  - npm install -g nyc
  - npm install -g sequelize-cli
script:
  - npm test
after_script:
  - npm run coverage
